const fs = require('fs');
let c = fs.readFileSync('src/pages/AIDesignPage.jsx', 'utf8');

c = c.replace(/â˜€ï¸ /g, '☀️')
     .replace(/ðŸ µ/g, '🍵')
     .replace(/ðŸ ™ï¸ /g, '🏙️')
     .replace(/Ä Ã¨n MÃ¢y Nghá»‡ Thuáº­t/g, 'Đèn Mây Nghệ Thuật')
     .replace(/â€”/g, '—')
     .replace(/Ä an xÆ°Æ¡ng cÃ¡/g, 'Đan xương cá')
     .replace(/XÆ°Æ¡ng cÃ¡/g, 'Xương cá')
     .replace(/Ä an máº¯t cÃ¡o/g, 'Đan mắt cáo')
     .replace(/Máº¯t cÃ¡o/g, 'Mắt cáo')
     .replace(/Ä an nong/g, 'Đan nong')
     .replace(/Ä an nan/g, 'Đan nan')
     .replace(/äººå\xAD—ç¼–/g, '人字编')
     .replace(/äººå\xAD—/g, '人字')
     .replace(/é•‚ç©ºç¼–/g, '镂空编')
     .replace(/é•‚ç©º/g, '镂空')
     .replace(/çŽ¯ç¼–/g, '环编')
     .replace(/çŽ¯/g, '环')
     .replace(/æ ¡ç¼–/g, '条编')
     .replace(/æ ¡/g, '条')
     .replace(/Ð Ð»Ð¾Ñ‡ÐºÐ°/g, 'Ёлочка')
     .replace(/Ð Ð¶ÑƒÑ€Ð½Ð¾Ðµ/g, 'Ажурное')
     .replace(/ÐšÐ¾Ð»ÑŒÑ†Ð¾/g, 'Кольцо')
     .replace(/ÐŸÐ»Ð°Ð½ÐºÐ¸/g, 'Планки')
     .replace(/å¤©ç„¶/g, '天然')
     .replace(/æŸ“è‰²/g, '染色')
     .replace(/æ¼†å™¨/g, '漆器')
     .replace(/Ð Ð°Ñ‚ÑƒÑ€Ð°Ð»ÑŒÐ½Ñ‹Ð¹/g, 'Натуральный')
     .replace(/Ð Ð°Ñ‚ÑƒÑ€\./g, 'Натур.')
     .replace(/ÐžÐºÑ€Ð°ÑˆÐµÐ½Ð½Ñ‹Ð¹/g, 'Окрашенный')
     .replace(/ÐžÐºÑ€Ð°Ñˆ\./g, 'Окраш.')
     .replace(/Ð›Ð°Ðº/g, 'Лак')
     .replace(/â ³/g, '⏳')
     .replace(/âœ“/g, '✓')
     .replace(/ðŸ“¦/g, '📦')
     .replace(/Ä‘/g, 'đ')
     .replace(/â†’/g, '→')
     .replace(/â ±/g, '⏳')
     .replace(/Chi phÃ\xAD nguyÃªn liá»‡u/g, 'Chi phí nguyên liệu')
     .replace(/Tá»•ng chi phÃ\xAD dá»± kiáº¿n/g, 'Tổng chi phí dự kiến');

fs.writeFileSync('src/pages/AIDesignPage.jsx', c, 'utf8');
console.log('done');
